import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# ^^^ pyforest auto-imports - don't write above this line
# Before your start:

- Comment as much as you can and use the resources
- Happy learning!

# Challenge 1 - Reading and Standardizing the Data

In this challenge we will work with image data and reduce the dimensions of the data to create a 2 dimensional plot. While we have not worked much with image data before, it can be represented as a numpy array where each pixel is assigned a numeric value. In this lesson, we will look at a dataset of cats and a dataset of dogs and see whether reducing them to two dimensions allows us to see if the data is separable. We will start by loading and processing the data. Run the cell below to load the two csv files and convert them into numpy arrays.

## Read the files into dataframes named `dogs` and `cats`

In [1]:
#your code here

# Import libraries
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from sklearn.preprocessing import StandardScaler

In [2]:
# Import the datasets
dogs = pd.read_csv('../data/dogs.csv')
cats = pd.read_csv('../data/cats.csv')

In [3]:
# Check the result for 'dogs'
dogs.head()

0    1    2    3    4    5    6    7    8    9  ...  4086  4087  4088  \
0  224  224  224  218  213  213  213  204  224  213  ...   130   123   113   
1  131  124  131  134  173  242  242  206   96   96  ...   104    96    89   
2  127  136  136  136  136  127  136  127  115  104  ...   136   144   161   
3  126  125  125  107   94   94  107   94   93   94  ...   125   126   136   
4  136  122  122  127  122  114  122  114  114  114  ...    94   127   147   

   4089  4090  4091  4092  4093  4094  4095  
0   100   100   100   100   106   100   100  
1    96   110   124    81    54   104   124  
2   161   144   136   115   104    89   104  
3   136   107    94    93    93    93    93  
4   173   162   147   147   136   114   108  

[5 rows x 4096 columns]

In [4]:
# Check the result for 'cats'
cats.head()

0    1    2    3    4    5    6    7    8    9  ...  4086  4087  4088  \
0   64   64   64   64   64   77   77   64   64   77  ...    22    36    36   
1   23   23   20   23   23   31   23   23   23   23  ...   101   101   101   
2  250  250  244  244  244  232  228  244  244  244  ...   232   232   232   
3  137  137  137  144  137  124  124  124  124  124  ...    53    55    66   
4   55   55   55   55   55   55   55   55   55   55  ...   146   134   134   

   4089  4090  4091  4092  4093  4094  4095  
0    36    47    77    64    61    61    61  
1   101    89    83    65    51    31     9  
2   232   232   232   232   244   232   244  
3    66    53    55    74    78   102   124  
4   103    64    52    45    52    45    52  

[5 rows x 4096 columns]

Next, we'll examine the shape of both the cats and the dogs arrays. Print out both shapes below.

In [5]:
# Your code here:

# Check the shape
print(f'The "dogs" dataset has {dogs.shape[0]} rows and {dogs.shape[1]} columns.')
print(f'The "cats" dataset has {cats.shape[0]} rows and {cats.shape[1]} columns.')

The "dogs" dataset has 80 rows and 4096 columns.
The "cats" dataset has 80 rows and 4096 columns.


What this means is that both arrays contain 80 images each (the number of rows). Each image is comprised of 64x64 pixels (so a total of 4096 pixels per image). The images have been flattened such that all 4096 are in a single row.

Print out row 0 of the cats dataframe to see what the pixels values look like.

In [6]:
# Your code here:

# Print the asnwer on the screen
cats[cats.index == 0]

0   1   2   3   4   5   6   7   8   9  ...  4086  4087  4088  4089  4090  \
0  64  64  64  64  64  77  77  64  64  77  ...    22    36    36    36    47   

   4091  4092  4093  4094  4095  
0    77    64    61    61    61  

[1 rows x 4096 columns]

Using `matplotlib` we can plot a single cat or a single dog. We do this by reshaping the observation vector back to a squared image and then using the `imshow` function.

Plot the image of the first cat and dog of your dataframes

_Extra: you can play with `imshow`'s argument `cmap` to see which colors are suitable for visualization_

In [7]:
# your code here

# Print the first dog
plt.imshow(dogs.iloc[0, :].values.reshape(64, 64), cmap='gray')

In [8]:
# Print the first cat
plt.imshow(cats.iloc[0, :].values.reshape(64, 64), cmap='gray')

Now concatenate the cats and dogs dataframes. Make sure to put dogs first. This should result in a dataframe containing 160 observations and 4096 dimensions.

In [9]:
# your code here

# Concatenate the dogs and cats dataframes
dogs_cats = pd.concat([dogs, cats])

# Check the result
dogs_cats

0    1    2    3    4    5    6    7    8    9  ...  4086  4087  4088  \
0   224  224  224  218  213  213  213  204  224  213  ...   130   123   113   
1   131  124  131  134  173  242  242  206   96   96  ...   104    96    89   
2   127  136  136  136  136  127  136  127  115  104  ...   136   144   161   
3   126  125  125  107   94   94  107   94   93   94  ...   125   126   136   
4   136  122  122  127  122  114  122  114  114  114  ...    94   127   147   
..  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...   ...   ...   
75   69   69   70   71   71   73   76   78   87   90  ...   124   107   104   
76   28   26   31   29   27   27   33   32   27   23  ...   106   110   120   
77   60   47   48   70   71   60   50   61   63   63  ...   161   160   149   
78  223  223  222  225  227  230  237  231  223  230  ...   170   171   177   
79  101  102  106  110  113  113  113  111  110  109  ...   110   104   121   

    4089  4090  4091  4092  4093  4094  4095  
0    100   100   100   100   106   100   100  
1     96   110   124    81    54   104   124  
2    161   144   136   115   104    89   104  
3    136   107    94    93    93    93    93  
4    173   162   147   147   136   114   108  
..   ...   ...   ...   ...   ...   ...   ...  
75   109   120   110    69    54    59    66  
76   124   126   128   128   136   139   144  
77   131   128   135   114    78    84   104  
78   179   180   181   180   180   178   177  
79    95    68    76   108   129   120   113  

[160 rows x 4096 columns]

Next, we would like to standardize our data. 

In order to do that, we will need to use the `StandardScaler` class from `sklearn.preprocessing` module.

Remember, we need to standardize the information for each pixel (which are the dimensions of our dataset) so that they can be compared in the PCA algorithm. Otherwise, the result would be dominated by the variable with the highest scale. 


In [10]:
# your code here

# Create the variable X
X = dogs_cats.rename(columns={str(i): f'pixel_{i}' for i in range(dogs_cats.shape[0])})

# Standardization
scaler = StandardScaler()
scaler.fit(X)
X_std = scaler.transform(X)

# Check the result for the standardization
X_std

array([[ 1.62729443,  1.71734864,  1.69367206, ..., -0.07659167,
        -0.12937266, -0.12602345],
       [ 0.38158288,  0.32579702,  0.41270021, ..., -0.88119103,
        -0.0700189 ,  0.22212766],
       [ 0.32800389,  0.49278322,  0.48156966, ..., -0.1075378 ,
        -0.29259552, -0.06799826],
       ...,
       [-0.56944422, -0.74569772, -0.73053274, ..., -0.50983748,
        -0.36678772, -0.06799826],
       [ 1.61389968,  1.70343313,  1.66612428, ...,  1.06841511,
         1.02802577,  0.99096135],
       [-0.02025956,  0.01965567,  0.06835293, ...,  0.27928882,
         0.16739617,  0.0625584 ]])

## Bonus

After standardizing your data, try visualizing your image again. Does the standardization changes your original image?

In [11]:
#%matplotlib notebook
# your code here

# Convert the 'X_std' to a dataframe
X_std_df = pd.DataFrame(X_std, columns=[f'pixel_{i}' for i in range(dogs_cats.shape[1])])

plt.imshow(X_std_df.iloc[0, :].values.reshape(64, 64), cmap='gray')
plt.show()

# Challenge 2 - Using PCA

Now that we have created a standardized matrix of cats and dogs, we'll find the two most important components in the data. 

Load the PCA from sklearn (https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.PCA.html) and apply the function to our standarized data. Create a PCA model with two components.

In [12]:
# Your code here:



After instantiating the `PCA class` and applying it to the standardized data, the results of your principal component analysis will be stored on the PCA object you've created (from the PCA class). 

# Challenge 3 - Plotting the Data

Now that we have reduced our cats and dogs arrays, we can plot the data in a way that the human eye can understand in 2-D. We can look at this plot to see whether there are differences between the cat and dog images. 

In the cell below, create a pandas dataframe containing the columns `pc1`, and `pc2` with the results of the first and second components of your results, respectively.

In [13]:
# Your code here:



Create a labels list. This list will be of size 160. The first 80 elements in the list will be the word `blue`, and the last 80 elements will be `red`. This will ensure that all dog observations will be colored in blue and all cats will be colored in red. Name this list `colors`.

In [14]:
# Your code here:



Create a scatter plot of `pc1` and `pc2` below. Use the `colors` list above to color the observations by setting `c=colors`.

In [15]:
# Your code here:



Do you see a clear separation between cats and dogs? Write your answer below.

In [16]:
# Your conclusions here:


# Evaluate the results

Calculate how much explained variance do the results of your PCA has lead to.  

In [17]:
# Your code here:

Explain with your own words what those values represent.

In [18]:
# your answer here:

# Bonus Challenge


Recreate your PCA using 20 components. You'll not be able to visualize the results this time, but the idea here is to plot a cumulative sum of your explained variance results. Follow the steps as before (i.e, create a dataframe containing the 20 components and so on)


What do you observe? How much of the information is retained after going from 4096 to 20 dimensions?

# Bonus Challenge 2

Use the `.inverse_transform()` method to the dataframe with the 20 components and store your results. The inverse transform takes the results of the PCA (the reduced dimension space) and take it back to the original space (with 4096 dimensions). This will be helpful for you to visualize how the PCA affected the original data.

In [19]:
# your code

Use the `imshow` to plot the first row of the `inverse_transform` of the results. Compare the results with the original image.

In [20]:
# your code

Change the value of the components above to have a feeling of the information retained (try 100 components).

The results above demonstrate the power of the PCA analysis. It takes the best combination of your columns in such a way that it preserves the most of its information. So, although you lose some of the information, you effectively reduce the number of dimensions on your dataset. This can be important both for visualization purposes as well as for understanding the importance of each feature.